### ISSUE TITLE
build_inventory_playbooks

### ISSUE THREAD

**Issue by jarrodpayne** [mrlesmithjr/Ansible#1]
Can you describe your process for [build_inventory_playbooks](https://github.com/mrlesmithjr/Ansible/tree/master/build_inventory_playbooks) a bit more in depth? I'm having trouble understanding where to start with these playbooks. For example, getting a VM cloned then provisioned is lost on me. Do you write playbooks that include bits of these, or use these directly from the cmd line?

**Comment by mrlesmithjr** [comment]
@jpdesigndev - That is a great question :) It has been so long since I have messed with these older Ansible playbooks. I will have to look through and see. I am sure there is a bunch of cleanup and more details around how to utilize these.

**Comment by jarrodpayne** [comment]
I see. Your project is the best resource I've found for in depth examples! I'm just having trouble gathering enough information around managing Linix VMs and vSphere. I've got a ton of bits and pieces, but nothing coherent (to an Ansible newbie). Any resources or comment once you've looked at your playbooks would be greatly appreciated!

**Comment by mrlesmithjr** [comment]
@jpdesigndev - Looking through this all again real quick it appears that what I was doing is running gather_vm_details.yml which would query vCenter for powered on VMs then pull in their IP addresses and use that info to build an inventory from vCenter which could then be used to run Ansible against. I don't think this set of playbooks was used to build/clone VMs.

**Comment by mrlesmithjr** [comment]
@jpdesigndev - much appreciated. I actually split most of these playbooks and such out into separate Git repos over time. Which is why I never went back to this mrlesmithjr/Ansible repo. Maybe I need to revisit once again :)
You can also checkout my blog if you have not already and I have quite a few examples of doing things there. Much more to come over time for sure as well.
http://everythingshouldbevirtual.com

**Comment by mrlesmithjr** [comment]
@jpdesigndev - Also...If there is anything in particular that you are looking to accomplish with Ansible let me know. I am always looking for ideas to pull together.

**Comment by jarrodpayne** [comment]
Thanks for the info! I'll take some time to peruse your other projects. Perhaps I'll come back with some concrete questions.
